# Generated by Django 5.0.2 on 2024-02-28 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='max_users',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='min_users',
            field=models.IntegerField(default=0),
        ),
    ]
